# Generated by Django 4.1.3 on 2023-09-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petronexa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
