# Generated by Django 3.2.3 on 2023-10-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petronexa_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment_content',
        ),
    ]
