# Generated by Django 3.2.3 on 2023-10-25 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petronexa_app', '0003_auto_20231025_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='user',
        ),
    ]
