# Generated by Django 3.2.3 on 2023-11-01 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petronexa_app', '0004_rename_username_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='map',
            new_name='map_url',
        ),
    ]
