# Generated by Django 4.1.3 on 2023-09-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petronexa_app', '0005_gasstation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GasStation',
        ),
        migrations.RemoveField(
            model_name='post',
            name='customer_service_rating',
        ),
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='customer_service',
            field=models.CharField(choices=[('poor', 'Poor'), ('average', 'Average'), ('good', 'Good'), ('excellent', 'Excellent')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
